// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkmibxpnxqdlauayexkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrbWlieHBueHFkbGF1YXlleGtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMDcwMzcsImV4cCI6MjA2ODc4MzAzN30.h6iCT6L9b5L0kk-r_u6Hyt3urVBw6P_MWwaKodpv9pY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});